# Generated by Django 5.1.6 on 2025-02-23 14:12

import user.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", user.manager.UserManager()),
            ],
        ),
    ]
